[build]
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/-/healthy"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[service]
internalPort = 9090
